// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl/ctrl.proto

// Protobuf Java Version: 3.25.5
package com.github.moxib.pomelo.proto.ctrl;

public final class CtrlProto {
  private CtrlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * ============================================================================
   * 控制类型枚举
   * ============================================================================
   * </pre>
   *
   * Protobuf enum {@code im.ctrl.CtrlType}
   */
  public enum CtrlType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CTRL_TYPE_UNKNOWN = 0;</code>
     */
    CTRL_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 踢下线
     * </pre>
     *
     * <code>CTRL_TYPE_KICK_OFFLINE = 1;</code>
     */
    CTRL_TYPE_KICK_OFFLINE(1),
    /**
     * <pre>
     * 强制登出
     * </pre>
     *
     * <code>CTRL_TYPE_FORCE_LOGOUT = 2;</code>
     */
    CTRL_TYPE_FORCE_LOGOUT(2),
    /**
     * <pre>
     * 通知
     * </pre>
     *
     * <code>CTRL_TYPE_NOTIFY = 3;</code>
     */
    CTRL_TYPE_NOTIFY(3),
    /**
     * <pre>
     * 同步
     * </pre>
     *
     * <code>CTRL_TYPE_SYNC = 4;</code>
     */
    CTRL_TYPE_SYNC(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CTRL_TYPE_UNKNOWN = 0;</code>
     */
    public static final int CTRL_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 踢下线
     * </pre>
     *
     * <code>CTRL_TYPE_KICK_OFFLINE = 1;</code>
     */
    public static final int CTRL_TYPE_KICK_OFFLINE_VALUE = 1;
    /**
     * <pre>
     * 强制登出
     * </pre>
     *
     * <code>CTRL_TYPE_FORCE_LOGOUT = 2;</code>
     */
    public static final int CTRL_TYPE_FORCE_LOGOUT_VALUE = 2;
    /**
     * <pre>
     * 通知
     * </pre>
     *
     * <code>CTRL_TYPE_NOTIFY = 3;</code>
     */
    public static final int CTRL_TYPE_NOTIFY_VALUE = 3;
    /**
     * <pre>
     * 同步
     * </pre>
     *
     * <code>CTRL_TYPE_SYNC = 4;</code>
     */
    public static final int CTRL_TYPE_SYNC_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CtrlType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CtrlType forNumber(int value) {
      switch (value) {
        case 0: return CTRL_TYPE_UNKNOWN;
        case 1: return CTRL_TYPE_KICK_OFFLINE;
        case 2: return CTRL_TYPE_FORCE_LOGOUT;
        case 3: return CTRL_TYPE_NOTIFY;
        case 4: return CTRL_TYPE_SYNC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CtrlType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CtrlType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CtrlType>() {
            public CtrlType findValueByNumber(int number) {
              return CtrlType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CtrlType[] VALUES = values();

    public static CtrlType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CtrlType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.ctrl.CtrlType)
  }

  public interface CtrlReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.ctrl.CtrlReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The enum numeric value on the wire for ctrlType.
     */
    int getCtrlTypeValue();
    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The ctrlType.
     */
    com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType getCtrlType();

    /**
     * <pre>
     * 目标用户
     * </pre>
     *
     * <code>string target_user = 2;</code>
     * @return The targetUser.
     */
    java.lang.String getTargetUser();
    /**
     * <pre>
     * 目标用户
     * </pre>
     *
     * <code>string target_user = 2;</code>
     * @return The bytes for targetUser.
     */
    com.google.protobuf.ByteString
        getTargetUserBytes();

    /**
     * <pre>
     * 控制载荷
     * </pre>
     *
     * <code>optional bytes payload = 3;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <pre>
     * 控制载荷
     * </pre>
     *
     * <code>optional bytes payload = 3;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * ============================================================================
   * 控制命令相关消息体
   * ============================================================================
   * </pre>
   *
   * Protobuf type {@code im.ctrl.CtrlReq}
   */
  public static final class CtrlReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.ctrl.CtrlReq)
      CtrlReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CtrlReq.newBuilder() to construct.
    private CtrlReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CtrlReq() {
      ctrlType_ = 0;
      targetUser_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CtrlReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.class, com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.Builder.class);
    }

    private int bitField0_;
    public static final int CTRL_TYPE_FIELD_NUMBER = 1;
    private int ctrlType_ = 0;
    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The enum numeric value on the wire for ctrlType.
     */
    @java.lang.Override public int getCtrlTypeValue() {
      return ctrlType_;
    }
    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The ctrlType.
     */
    @java.lang.Override public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType getCtrlType() {
      com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType result = com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.forNumber(ctrlType_);
      return result == null ? com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.UNRECOGNIZED : result;
    }

    public static final int TARGET_USER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object targetUser_ = "";
    /**
     * <pre>
     * 目标用户
     * </pre>
     *
     * <code>string target_user = 2;</code>
     * @return The targetUser.
     */
    @java.lang.Override
    public java.lang.String getTargetUser() {
      java.lang.Object ref = targetUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 目标用户
     * </pre>
     *
     * <code>string target_user = 2;</code>
     * @return The bytes for targetUser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetUserBytes() {
      java.lang.Object ref = targetUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 控制载荷
     * </pre>
     *
     * <code>optional bytes payload = 3;</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 控制载荷
     * </pre>
     *
     * <code>optional bytes payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ctrlType_ != com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.CTRL_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(1, ctrlType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetUser_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, targetUser_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ctrlType_ != com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.CTRL_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ctrlType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetUser_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, targetUser_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq other = (com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq) obj;

      if (ctrlType_ != other.ctrlType_) return false;
      if (!getTargetUser()
          .equals(other.getTargetUser())) return false;
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CTRL_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + ctrlType_;
      hash = (37 * hash) + TARGET_USER_FIELD_NUMBER;
      hash = (53 * hash) + getTargetUser().hashCode();
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ============================================================================
     * 控制命令相关消息体
     * ============================================================================
     * </pre>
     *
     * Protobuf type {@code im.ctrl.CtrlReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.ctrl.CtrlReq)
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.class, com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ctrlType_ = 0;
        targetUser_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlReq_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq build() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq buildPartial() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq result = new com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ctrlType_ = ctrlType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.targetUser_ = targetUser_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payload_ = payload_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq) {
          return mergeFrom((com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq other) {
        if (other == com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq.getDefaultInstance()) return this;
        if (other.ctrlType_ != 0) {
          setCtrlTypeValue(other.getCtrlTypeValue());
        }
        if (!other.getTargetUser().isEmpty()) {
          targetUser_ = other.targetUser_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ctrlType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                targetUser_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int ctrlType_ = 0;
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @return The enum numeric value on the wire for ctrlType.
       */
      @java.lang.Override public int getCtrlTypeValue() {
        return ctrlType_;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @param value The enum numeric value on the wire for ctrlType to set.
       * @return This builder for chaining.
       */
      public Builder setCtrlTypeValue(int value) {
        ctrlType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @return The ctrlType.
       */
      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType getCtrlType() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType result = com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.forNumber(ctrlType_);
        return result == null ? com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.UNRECOGNIZED : result;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @param value The ctrlType to set.
       * @return This builder for chaining.
       */
      public Builder setCtrlType(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        ctrlType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtrlType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ctrlType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object targetUser_ = "";
      /**
       * <pre>
       * 目标用户
       * </pre>
       *
       * <code>string target_user = 2;</code>
       * @return The targetUser.
       */
      public java.lang.String getTargetUser() {
        java.lang.Object ref = targetUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 目标用户
       * </pre>
       *
       * <code>string target_user = 2;</code>
       * @return The bytes for targetUser.
       */
      public com.google.protobuf.ByteString
          getTargetUserBytes() {
        java.lang.Object ref = targetUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 目标用户
       * </pre>
       *
       * <code>string target_user = 2;</code>
       * @param value The targetUser to set.
       * @return This builder for chaining.
       */
      public Builder setTargetUser(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        targetUser_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标用户
       * </pre>
       *
       * <code>string target_user = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetUser() {
        targetUser_ = getDefaultInstance().getTargetUser();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标用户
       * </pre>
       *
       * <code>string target_user = 2;</code>
       * @param value The bytes for targetUser to set.
       * @return This builder for chaining.
       */
      public Builder setTargetUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        targetUser_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>optional bytes payload = 3;</code>
       * @return Whether the payload field is set.
       */
      @java.lang.Override
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>optional bytes payload = 3;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>optional bytes payload = 3;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>optional bytes payload = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.ctrl.CtrlReq)
    }

    // @@protoc_insertion_point(class_scope:im.ctrl.CtrlReq)
    private static final com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq();
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CtrlReq>
        PARSER = new com.google.protobuf.AbstractParser<CtrlReq>() {
      @java.lang.Override
      public CtrlReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CtrlReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CtrlReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CtrlRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.ctrl.CtrlResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 响应码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 控制载荷响应
     * </pre>
     *
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code im.ctrl.CtrlResp}
   */
  public static final class CtrlResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.ctrl.CtrlResp)
      CtrlRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CtrlResp.newBuilder() to construct.
    private CtrlResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CtrlResp() {
      message_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CtrlResp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.class, com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <pre>
     * 响应码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 控制载荷响应
     * </pre>
     *
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp other = (com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.ctrl.CtrlResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.ctrl.CtrlResp)
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.class, com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlResp_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp build() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp buildPartial() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp result = new com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp) {
          return mergeFrom((com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp other) {
        if (other == com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 控制载荷响应
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * 控制载荷响应
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 控制载荷响应
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.ctrl.CtrlResp)
    }

    // @@protoc_insertion_point(class_scope:im.ctrl.CtrlResp)
    private static final com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp();
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CtrlResp>
        PARSER = new com.google.protobuf.AbstractParser<CtrlResp>() {
      @java.lang.Override
      public CtrlResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CtrlResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CtrlResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CtrlNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.ctrl.CtrlNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The enum numeric value on the wire for ctrlType.
     */
    int getCtrlTypeValue();
    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The ctrlType.
     */
    com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType getCtrlType();

    /**
     * <pre>
     * 推送原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <pre>
     * 推送原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();

    /**
     * <pre>
     * 控制载荷
     * </pre>
     *
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code im.ctrl.CtrlNotify}
   */
  public static final class CtrlNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.ctrl.CtrlNotify)
      CtrlNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CtrlNotify.newBuilder() to construct.
    private CtrlNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CtrlNotify() {
      ctrlType_ = 0;
      reason_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CtrlNotify();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.class, com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.Builder.class);
    }

    public static final int CTRL_TYPE_FIELD_NUMBER = 1;
    private int ctrlType_ = 0;
    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The enum numeric value on the wire for ctrlType.
     */
    @java.lang.Override public int getCtrlTypeValue() {
      return ctrlType_;
    }
    /**
     * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
     * @return The ctrlType.
     */
    @java.lang.Override public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType getCtrlType() {
      com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType result = com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.forNumber(ctrlType_);
      return result == null ? com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.UNRECOGNIZED : result;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object reason_ = "";
    /**
     * <pre>
     * 推送原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 推送原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 控制载荷
     * </pre>
     *
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ctrlType_ != com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.CTRL_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(1, ctrlType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reason_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ctrlType_ != com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.CTRL_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ctrlType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reason_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify other = (com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify) obj;

      if (ctrlType_ != other.ctrlType_) return false;
      if (!getReason()
          .equals(other.getReason())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CTRL_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + ctrlType_;
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.ctrl.CtrlNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.ctrl.CtrlNotify)
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlNotify_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.class, com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ctrlType_ = 0;
        reason_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.internal_static_im_ctrl_CtrlNotify_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify build() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify buildPartial() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify result = new com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ctrlType_ = ctrlType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reason_ = reason_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify) {
          return mergeFrom((com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify other) {
        if (other == com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify.getDefaultInstance()) return this;
        if (other.ctrlType_ != 0) {
          setCtrlTypeValue(other.getCtrlTypeValue());
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ctrlType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                reason_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int ctrlType_ = 0;
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @return The enum numeric value on the wire for ctrlType.
       */
      @java.lang.Override public int getCtrlTypeValue() {
        return ctrlType_;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @param value The enum numeric value on the wire for ctrlType to set.
       * @return This builder for chaining.
       */
      public Builder setCtrlTypeValue(int value) {
        ctrlType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @return The ctrlType.
       */
      @java.lang.Override
      public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType getCtrlType() {
        com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType result = com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.forNumber(ctrlType_);
        return result == null ? com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType.UNRECOGNIZED : result;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @param value The ctrlType to set.
       * @return This builder for chaining.
       */
      public Builder setCtrlType(com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        ctrlType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.im.ctrl.CtrlType ctrl_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtrlType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ctrlType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <pre>
       * 推送原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return The reason.
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 推送原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return The bytes for reason.
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 推送原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 推送原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        reason_ = getDefaultInstance().getReason();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 推送原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 控制载荷
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.ctrl.CtrlNotify)
    }

    // @@protoc_insertion_point(class_scope:im.ctrl.CtrlNotify)
    private static final com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify();
    }

    public static com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CtrlNotify>
        PARSER = new com.google.protobuf.AbstractParser<CtrlNotify>() {
      @java.lang.Override
      public CtrlNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CtrlNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CtrlNotify> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.ctrl.CtrlProto.CtrlNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_ctrl_CtrlReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_ctrl_CtrlReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_ctrl_CtrlResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_ctrl_CtrlResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_ctrl_CtrlNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_ctrl_CtrlNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ctrl/ctrl.proto\022\007im.ctrl\"f\n\007CtrlReq\022$\n" +
      "\tctrl_type\030\001 \001(\0162\021.im.ctrl.CtrlType\022\023\n\013t" +
      "arget_user\030\002 \001(\t\022\024\n\007payload\030\003 \001(\014H\000\210\001\001B\n" +
      "\n\010_payload\":\n\010CtrlResp\022\014\n\004code\030\001 \001(\005\022\017\n\007" +
      "message\030\002 \001(\t\022\017\n\007payload\030\003 \001(\014\"S\n\nCtrlNo" +
      "tify\022$\n\tctrl_type\030\001 \001(\0162\021.im.ctrl.CtrlTy" +
      "pe\022\016\n\006reason\030\002 \001(\t\022\017\n\007payload\030\003 \001(\014*\203\001\n\010" +
      "CtrlType\022\025\n\021CTRL_TYPE_UNKNOWN\020\000\022\032\n\026CTRL_" +
      "TYPE_KICK_OFFLINE\020\001\022\032\n\026CTRL_TYPE_FORCE_L" +
      "OGOUT\020\002\022\024\n\020CTRL_TYPE_NOTIFY\020\003\022\022\n\016CTRL_TY" +
      "PE_SYNC\020\004B/\n\"com.github.moxib.pomelo.pro" +
      "to.ctrlB\tCtrlProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_ctrl_CtrlReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_ctrl_CtrlReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_ctrl_CtrlReq_descriptor,
        new java.lang.String[] { "CtrlType", "TargetUser", "Payload", });
    internal_static_im_ctrl_CtrlResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_im_ctrl_CtrlResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_ctrl_CtrlResp_descriptor,
        new java.lang.String[] { "Code", "Message", "Payload", });
    internal_static_im_ctrl_CtrlNotify_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_im_ctrl_CtrlNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_ctrl_CtrlNotify_descriptor,
        new java.lang.String[] { "CtrlType", "Reason", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
