// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat/heartbeat.proto

// Protobuf Java Version: 3.25.5
package com.github.moxib.pomelo.proto.heartbeat;

public final class HeartbeatProto {
  private HeartbeatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.heartbeat.Ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 客户端时间戳
     * </pre>
     *
     * <code>int64 client_time = 1;</code>
     * @return The clientTime.
     */
    long getClientTime();
  }
  /**
   * <pre>
   * ============================================================================
   * 心跳相关消息体
   * ============================================================================
   * </pre>
   *
   * Protobuf type {@code im.heartbeat.Ping}
   */
  public static final class Ping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.heartbeat.Ping)
      PingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ping.newBuilder() to construct.
    private Ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ping() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Ping();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Ping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.class, com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.Builder.class);
    }

    public static final int CLIENT_TIME_FIELD_NUMBER = 1;
    private long clientTime_ = 0L;
    /**
     * <pre>
     * 客户端时间戳
     * </pre>
     *
     * <code>int64 client_time = 1;</code>
     * @return The clientTime.
     */
    @java.lang.Override
    public long getClientTime() {
      return clientTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientTime_ != 0L) {
        output.writeInt64(1, clientTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping other = (com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping) obj;

      if (getClientTime()
          != other.getClientTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ============================================================================
     * 心跳相关消息体
     * ============================================================================
     * </pre>
     *
     * Protobuf type {@code im.heartbeat.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.heartbeat.Ping)
        com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Ping_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.class, com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Ping_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping build() {
        com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping buildPartial() {
        com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping result = new com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientTime_ = clientTime_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping) {
          return mergeFrom((com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping other) {
        if (other == com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping.getDefaultInstance()) return this;
        if (other.getClientTime() != 0L) {
          setClientTime(other.getClientTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                clientTime_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long clientTime_ ;
      /**
       * <pre>
       * 客户端时间戳
       * </pre>
       *
       * <code>int64 client_time = 1;</code>
       * @return The clientTime.
       */
      @java.lang.Override
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <pre>
       * 客户端时间戳
       * </pre>
       *
       * <code>int64 client_time = 1;</code>
       * @param value The clientTime to set.
       * @return This builder for chaining.
       */
      public Builder setClientTime(long value) {

        clientTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端时间戳
       * </pre>
       *
       * <code>int64 client_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.heartbeat.Ping)
    }

    // @@protoc_insertion_point(class_scope:im.heartbeat.Ping)
    private static final com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping();
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ping>
        PARSER = new com.google.protobuf.AbstractParser<Ping>() {
      @java.lang.Override
      public Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ping> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.heartbeat.Pong)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器时间戳
     * </pre>
     *
     * <code>int64 server_time = 1;</code>
     * @return The serverTime.
     */
    long getServerTime();

    /**
     * <pre>
     * 回显客户端时间
     * </pre>
     *
     * <code>int64 client_time = 2;</code>
     * @return The clientTime.
     */
    long getClientTime();
  }
  /**
   * Protobuf type {@code im.heartbeat.Pong}
   */
  public static final class Pong extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.heartbeat.Pong)
      PongOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pong.newBuilder() to construct.
    private Pong(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pong() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pong();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Pong_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.class, com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.Builder.class);
    }

    public static final int SERVER_TIME_FIELD_NUMBER = 1;
    private long serverTime_ = 0L;
    /**
     * <pre>
     * 服务器时间戳
     * </pre>
     *
     * <code>int64 server_time = 1;</code>
     * @return The serverTime.
     */
    @java.lang.Override
    public long getServerTime() {
      return serverTime_;
    }

    public static final int CLIENT_TIME_FIELD_NUMBER = 2;
    private long clientTime_ = 0L;
    /**
     * <pre>
     * 回显客户端时间
     * </pre>
     *
     * <code>int64 client_time = 2;</code>
     * @return The clientTime.
     */
    @java.lang.Override
    public long getClientTime() {
      return clientTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverTime_ != 0L) {
        output.writeInt64(1, serverTime_);
      }
      if (clientTime_ != 0L) {
        output.writeInt64(2, clientTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, serverTime_);
      }
      if (clientTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, clientTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong other = (com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong) obj;

      if (getServerTime()
          != other.getServerTime()) return false;
      if (getClientTime()
          != other.getClientTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTime());
      hash = (37 * hash) + CLIENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.heartbeat.Pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.heartbeat.Pong)
        com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.PongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Pong_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.class, com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverTime_ = 0L;
        clientTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.internal_static_im_heartbeat_Pong_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong build() {
        com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong buildPartial() {
        com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong result = new com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverTime_ = serverTime_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.clientTime_ = clientTime_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong) {
          return mergeFrom((com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong other) {
        if (other == com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong.getDefaultInstance()) return this;
        if (other.getServerTime() != 0L) {
          setServerTime(other.getServerTime());
        }
        if (other.getClientTime() != 0L) {
          setClientTime(other.getClientTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serverTime_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                clientTime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long serverTime_ ;
      /**
       * <pre>
       * 服务器时间戳
       * </pre>
       *
       * <code>int64 server_time = 1;</code>
       * @return The serverTime.
       */
      @java.lang.Override
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       * 服务器时间戳
       * </pre>
       *
       * <code>int64 server_time = 1;</code>
       * @param value The serverTime to set.
       * @return This builder for chaining.
       */
      public Builder setServerTime(long value) {

        serverTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器时间戳
       * </pre>
       *
       * <code>int64 server_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0L;
        onChanged();
        return this;
      }

      private long clientTime_ ;
      /**
       * <pre>
       * 回显客户端时间
       * </pre>
       *
       * <code>int64 client_time = 2;</code>
       * @return The clientTime.
       */
      @java.lang.Override
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <pre>
       * 回显客户端时间
       * </pre>
       *
       * <code>int64 client_time = 2;</code>
       * @param value The clientTime to set.
       * @return This builder for chaining.
       */
      public Builder setClientTime(long value) {

        clientTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回显客户端时间
       * </pre>
       *
       * <code>int64 client_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.heartbeat.Pong)
    }

    // @@protoc_insertion_point(class_scope:im.heartbeat.Pong)
    private static final com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong();
    }

    public static com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pong>
        PARSER = new com.google.protobuf.AbstractParser<Pong>() {
      @java.lang.Override
      public Pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Pong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pong> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.heartbeat.HeartbeatProto.Pong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_heartbeat_Ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_heartbeat_Ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_heartbeat_Pong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_heartbeat_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031heartbeat/heartbeat.proto\022\014im.heartbea" +
      "t\"\033\n\004Ping\022\023\n\013client_time\030\001 \001(\003\"0\n\004Pong\022\023" +
      "\n\013server_time\030\001 \001(\003\022\023\n\013client_time\030\002 \001(\003" +
      "B9\n\'com.github.moxib.pomelo.proto.heartb" +
      "eatB\016HeartbeatProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_heartbeat_Ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_heartbeat_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_heartbeat_Ping_descriptor,
        new java.lang.String[] { "ClientTime", });
    internal_static_im_heartbeat_Pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_im_heartbeat_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_heartbeat_Pong_descriptor,
        new java.lang.String[] { "ServerTime", "ClientTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
