// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload/upload.proto

// Protobuf Java Version: 3.25.5
package com.github.moxib.pomelo.proto.upload;

public final class UploadProto {
  private UploadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UploadReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.upload.UploadReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 媒体类型（MsgType: 2=image 3=voice 4=video 5=file 6=emoji）
     * </pre>
     *
     * <code>int32 media_type = 1;</code>
     * @return The mediaType.
     */
    int getMediaType();

    /**
     * <pre>
     * 原始文件名（含扩展名）
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <pre>
     * 原始文件名（含扩展名）
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <pre>
     * 文件大小（字节）
     * </pre>
     *
     * <code>int64 size = 3;</code>
     * @return The size.
     */
    long getSize();

    /**
     * <pre>
     * MIME 类型（可选）
     * </pre>
     *
     * <code>string content_type = 4;</code>
     * @return The contentType.
     */
    java.lang.String getContentType();
    /**
     * <pre>
     * MIME 类型（可选）
     * </pre>
     *
     * <code>string content_type = 4;</code>
     * @return The bytes for contentType.
     */
    com.google.protobuf.ByteString
        getContentTypeBytes();
  }
  /**
   * <pre>
   * ============================================================================
   * 媒体上传预签名
   * ============================================================================
   * </pre>
   *
   * Protobuf type {@code im.upload.UploadReq}
   */
  public static final class UploadReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.upload.UploadReq)
      UploadReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadReq.newBuilder() to construct.
    private UploadReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadReq() {
      fileName_ = "";
      contentType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UploadReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.class, com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.Builder.class);
    }

    public static final int MEDIA_TYPE_FIELD_NUMBER = 1;
    private int mediaType_ = 0;
    /**
     * <pre>
     * 媒体类型（MsgType: 2=image 3=voice 4=video 5=file 6=emoji）
     * </pre>
     *
     * <code>int32 media_type = 1;</code>
     * @return The mediaType.
     */
    @java.lang.Override
    public int getMediaType() {
      return mediaType_;
    }

    public static final int FILE_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <pre>
     * 原始文件名（含扩展名）
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 原始文件名（含扩展名）
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private long size_ = 0L;
    /**
     * <pre>
     * 文件大小（字节）
     * </pre>
     *
     * <code>int64 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }

    public static final int CONTENT_TYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contentType_ = "";
    /**
     * <pre>
     * MIME 类型（可选）
     * </pre>
     *
     * <code>string content_type = 4;</code>
     * @return The contentType.
     */
    @java.lang.Override
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * MIME 类型（可选）
     * </pre>
     *
     * <code>string content_type = 4;</code>
     * @return The bytes for contentType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mediaType_ != 0) {
        output.writeInt32(1, mediaType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
      }
      if (size_ != 0L) {
        output.writeInt64(3, size_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, contentType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mediaType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mediaType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, size_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, contentType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq other = (com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq) obj;

      if (getMediaType()
          != other.getMediaType()) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (getSize()
          != other.getSize()) return false;
      if (!getContentType()
          .equals(other.getContentType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDIA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMediaType();
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (37 * hash) + CONTENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ============================================================================
     * 媒体上传预签名
     * ============================================================================
     * </pre>
     *
     * Protobuf type {@code im.upload.UploadReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.upload.UploadReq)
        com.github.moxib.pomelo.proto.upload.UploadProto.UploadReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.class, com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mediaType_ = 0;
        fileName_ = "";
        size_ = 0L;
        contentType_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadReq_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq build() {
        com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq buildPartial() {
        com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq result = new com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mediaType_ = mediaType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileName_ = fileName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.size_ = size_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.contentType_ = contentType_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq) {
          return mergeFrom((com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq other) {
        if (other == com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq.getDefaultInstance()) return this;
        if (other.getMediaType() != 0) {
          setMediaType(other.getMediaType());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (!other.getContentType().isEmpty()) {
          contentType_ = other.contentType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                mediaType_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                size_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                contentType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int mediaType_ ;
      /**
       * <pre>
       * 媒体类型（MsgType: 2=image 3=voice 4=video 5=file 6=emoji）
       * </pre>
       *
       * <code>int32 media_type = 1;</code>
       * @return The mediaType.
       */
      @java.lang.Override
      public int getMediaType() {
        return mediaType_;
      }
      /**
       * <pre>
       * 媒体类型（MsgType: 2=image 3=voice 4=video 5=file 6=emoji）
       * </pre>
       *
       * <code>int32 media_type = 1;</code>
       * @param value The mediaType to set.
       * @return This builder for chaining.
       */
      public Builder setMediaType(int value) {

        mediaType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 媒体类型（MsgType: 2=image 3=voice 4=video 5=file 6=emoji）
       * </pre>
       *
       * <code>int32 media_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mediaType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       * 原始文件名（含扩展名）
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 原始文件名（含扩展名）
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 原始文件名（含扩展名）
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 原始文件名（含扩展名）
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 原始文件名（含扩展名）
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <pre>
       * 文件大小（字节）
       * </pre>
       *
       * <code>int64 size = 3;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }
      /**
       * <pre>
       * 文件大小（字节）
       * </pre>
       *
       * <code>int64 size = 3;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {

        size_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件大小（字节）
       * </pre>
       *
       * <code>int64 size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object contentType_ = "";
      /**
       * <pre>
       * MIME 类型（可选）
       * </pre>
       *
       * <code>string content_type = 4;</code>
       * @return The contentType.
       */
      public java.lang.String getContentType() {
        java.lang.Object ref = contentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * MIME 类型（可选）
       * </pre>
       *
       * <code>string content_type = 4;</code>
       * @return The bytes for contentType.
       */
      public com.google.protobuf.ByteString
          getContentTypeBytes() {
        java.lang.Object ref = contentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * MIME 类型（可选）
       * </pre>
       *
       * <code>string content_type = 4;</code>
       * @param value The contentType to set.
       * @return This builder for chaining.
       */
      public Builder setContentType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contentType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * MIME 类型（可选）
       * </pre>
       *
       * <code>string content_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentType() {
        contentType_ = getDefaultInstance().getContentType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * MIME 类型（可选）
       * </pre>
       *
       * <code>string content_type = 4;</code>
       * @param value The bytes for contentType to set.
       * @return This builder for chaining.
       */
      public Builder setContentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contentType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.upload.UploadReq)
    }

    // @@protoc_insertion_point(class_scope:im.upload.UploadReq)
    private static final com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq();
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadReq>
        PARSER = new com.google.protobuf.AbstractParser<UploadReq>() {
      @java.lang.Override
      public UploadReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UploadReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.upload.UploadProto.UploadReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UploadRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.upload.UploadResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 响应码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 稳定 object key
     * </pre>
     *
     * <code>string object_key = 3;</code>
     * @return The objectKey.
     */
    java.lang.String getObjectKey();
    /**
     * <pre>
     * 稳定 object key
     * </pre>
     *
     * <code>string object_key = 3;</code>
     * @return The bytes for objectKey.
     */
    com.google.protobuf.ByteString
        getObjectKeyBytes();

    /**
     * <pre>
     * presigned PUT URL
     * </pre>
     *
     * <code>string presigned_url = 4;</code>
     * @return The presignedUrl.
     */
    java.lang.String getPresignedUrl();
    /**
     * <pre>
     * presigned PUT URL
     * </pre>
     *
     * <code>string presigned_url = 4;</code>
     * @return The bytes for presignedUrl.
     */
    com.google.protobuf.ByteString
        getPresignedUrlBytes();

    /**
     * <pre>
     * 过期时间（Unix 毫秒）
     * </pre>
     *
     * <code>int64 expire_at = 5;</code>
     * @return The expireAt.
     */
    long getExpireAt();
  }
  /**
   * Protobuf type {@code im.upload.UploadResp}
   */
  public static final class UploadResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.upload.UploadResp)
      UploadRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadResp.newBuilder() to construct.
    private UploadResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadResp() {
      message_ = "";
      objectKey_ = "";
      presignedUrl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UploadResp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.class, com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <pre>
     * 响应码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OBJECT_KEY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object objectKey_ = "";
    /**
     * <pre>
     * 稳定 object key
     * </pre>
     *
     * <code>string object_key = 3;</code>
     * @return The objectKey.
     */
    @java.lang.Override
    public java.lang.String getObjectKey() {
      java.lang.Object ref = objectKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 稳定 object key
     * </pre>
     *
     * <code>string object_key = 3;</code>
     * @return The bytes for objectKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectKeyBytes() {
      java.lang.Object ref = objectKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRESIGNED_URL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object presignedUrl_ = "";
    /**
     * <pre>
     * presigned PUT URL
     * </pre>
     *
     * <code>string presigned_url = 4;</code>
     * @return The presignedUrl.
     */
    @java.lang.Override
    public java.lang.String getPresignedUrl() {
      java.lang.Object ref = presignedUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        presignedUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * presigned PUT URL
     * </pre>
     *
     * <code>string presigned_url = 4;</code>
     * @return The bytes for presignedUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPresignedUrlBytes() {
      java.lang.Object ref = presignedUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        presignedUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRE_AT_FIELD_NUMBER = 5;
    private long expireAt_ = 0L;
    /**
     * <pre>
     * 过期时间（Unix 毫秒）
     * </pre>
     *
     * <code>int64 expire_at = 5;</code>
     * @return The expireAt.
     */
    @java.lang.Override
    public long getExpireAt() {
      return expireAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, objectKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(presignedUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, presignedUrl_);
      }
      if (expireAt_ != 0L) {
        output.writeInt64(5, expireAt_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, objectKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(presignedUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, presignedUrl_);
      }
      if (expireAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, expireAt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp other = (com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getObjectKey()
          .equals(other.getObjectKey())) return false;
      if (!getPresignedUrl()
          .equals(other.getPresignedUrl())) return false;
      if (getExpireAt()
          != other.getExpireAt()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + OBJECT_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getObjectKey().hashCode();
      hash = (37 * hash) + PRESIGNED_URL_FIELD_NUMBER;
      hash = (53 * hash) + getPresignedUrl().hashCode();
      hash = (37 * hash) + EXPIRE_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireAt());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.upload.UploadResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.upload.UploadResp)
        com.github.moxib.pomelo.proto.upload.UploadProto.UploadRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.class, com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        objectKey_ = "";
        presignedUrl_ = "";
        expireAt_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.internal_static_im_upload_UploadResp_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp build() {
        com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp buildPartial() {
        com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp result = new com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.objectKey_ = objectKey_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.presignedUrl_ = presignedUrl_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.expireAt_ = expireAt_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp) {
          return mergeFrom((com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp other) {
        if (other == com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getObjectKey().isEmpty()) {
          objectKey_ = other.objectKey_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPresignedUrl().isEmpty()) {
          presignedUrl_ = other.presignedUrl_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getExpireAt() != 0L) {
          setExpireAt(other.getExpireAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                objectKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                presignedUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                expireAt_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object objectKey_ = "";
      /**
       * <pre>
       * 稳定 object key
       * </pre>
       *
       * <code>string object_key = 3;</code>
       * @return The objectKey.
       */
      public java.lang.String getObjectKey() {
        java.lang.Object ref = objectKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 稳定 object key
       * </pre>
       *
       * <code>string object_key = 3;</code>
       * @return The bytes for objectKey.
       */
      public com.google.protobuf.ByteString
          getObjectKeyBytes() {
        java.lang.Object ref = objectKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 稳定 object key
       * </pre>
       *
       * <code>string object_key = 3;</code>
       * @param value The objectKey to set.
       * @return This builder for chaining.
       */
      public Builder setObjectKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        objectKey_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 稳定 object key
       * </pre>
       *
       * <code>string object_key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectKey() {
        objectKey_ = getDefaultInstance().getObjectKey();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 稳定 object key
       * </pre>
       *
       * <code>string object_key = 3;</code>
       * @param value The bytes for objectKey to set.
       * @return This builder for chaining.
       */
      public Builder setObjectKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        objectKey_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object presignedUrl_ = "";
      /**
       * <pre>
       * presigned PUT URL
       * </pre>
       *
       * <code>string presigned_url = 4;</code>
       * @return The presignedUrl.
       */
      public java.lang.String getPresignedUrl() {
        java.lang.Object ref = presignedUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          presignedUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * presigned PUT URL
       * </pre>
       *
       * <code>string presigned_url = 4;</code>
       * @return The bytes for presignedUrl.
       */
      public com.google.protobuf.ByteString
          getPresignedUrlBytes() {
        java.lang.Object ref = presignedUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          presignedUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * presigned PUT URL
       * </pre>
       *
       * <code>string presigned_url = 4;</code>
       * @param value The presignedUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPresignedUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        presignedUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * presigned PUT URL
       * </pre>
       *
       * <code>string presigned_url = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPresignedUrl() {
        presignedUrl_ = getDefaultInstance().getPresignedUrl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * presigned PUT URL
       * </pre>
       *
       * <code>string presigned_url = 4;</code>
       * @param value The bytes for presignedUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPresignedUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        presignedUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private long expireAt_ ;
      /**
       * <pre>
       * 过期时间（Unix 毫秒）
       * </pre>
       *
       * <code>int64 expire_at = 5;</code>
       * @return The expireAt.
       */
      @java.lang.Override
      public long getExpireAt() {
        return expireAt_;
      }
      /**
       * <pre>
       * 过期时间（Unix 毫秒）
       * </pre>
       *
       * <code>int64 expire_at = 5;</code>
       * @param value The expireAt to set.
       * @return This builder for chaining.
       */
      public Builder setExpireAt(long value) {

        expireAt_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 过期时间（Unix 毫秒）
       * </pre>
       *
       * <code>int64 expire_at = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpireAt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        expireAt_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.upload.UploadResp)
    }

    // @@protoc_insertion_point(class_scope:im.upload.UploadResp)
    private static final com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp();
    }

    public static com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadResp>
        PARSER = new com.google.protobuf.AbstractParser<UploadResp>() {
      @java.lang.Override
      public UploadResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UploadResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.upload.UploadProto.UploadResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_upload_UploadReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_upload_UploadReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_upload_UploadResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_upload_UploadResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023upload/upload.proto\022\tim.upload\"V\n\tUplo" +
      "adReq\022\022\n\nmedia_type\030\001 \001(\005\022\021\n\tfile_name\030\002" +
      " \001(\t\022\014\n\004size\030\003 \001(\003\022\024\n\014content_type\030\004 \001(\t" +
      "\"i\n\nUploadResp\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030" +
      "\002 \001(\t\022\022\n\nobject_key\030\003 \001(\t\022\025\n\rpresigned_u" +
      "rl\030\004 \001(\t\022\021\n\texpire_at\030\005 \001(\003B3\n$com.githu" +
      "b.moxib.pomelo.proto.uploadB\013UploadProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_upload_UploadReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_upload_UploadReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_upload_UploadReq_descriptor,
        new java.lang.String[] { "MediaType", "FileName", "Size", "ContentType", });
    internal_static_im_upload_UploadResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_im_upload_UploadResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_upload_UploadResp_descriptor,
        new java.lang.String[] { "Code", "Message", "ObjectKey", "PresignedUrl", "ExpireAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
