// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

// Protobuf Java Version: 3.25.5
package com.github.moxib.pomelo.proto.common;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * ============================================================================
   * 命令字（Cmd）枚举定义
   * ============================================================================
   * </pre>
   *
   * Protobuf enum {@code im.common.Cmd}
   */
  public enum Cmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CMD_UNKNOWN = 0;</code>
     */
    CMD_UNKNOWN(0),
    /**
     * <pre>
     * 认证相关
     * </pre>
     *
     * <code>CMD_AUTH_REQ = 1;</code>
     */
    CMD_AUTH_REQ(1),
    /**
     * <pre>
     * S→C 认证响应
     * </pre>
     *
     * <code>CMD_AUTH_RESP = 2;</code>
     */
    CMD_AUTH_RESP(2),
    /**
     * <pre>
     * C→S 登出请求
     * </pre>
     *
     * <code>CMD_LOGOUT_REQ = 3;</code>
     */
    CMD_LOGOUT_REQ(3),
    /**
     * <pre>
     * S→C 登出响应
     * </pre>
     *
     * <code>CMD_LOGOUT_RESP = 4;</code>
     */
    CMD_LOGOUT_RESP(4),
    /**
     * <pre>
     * 单聊相关
     * </pre>
     *
     * <code>CMD_C2C_REQ = 16;</code>
     */
    CMD_C2C_REQ(16),
    /**
     * <pre>
     * S→C 单聊发送响应
     * </pre>
     *
     * <code>CMD_C2C_RESP = 17;</code>
     */
    CMD_C2C_RESP(17),
    /**
     * <pre>
     * S→C 单聊消息推送
     * </pre>
     *
     * <code>CMD_C2C_NOTIFY = 18;</code>
     */
    CMD_C2C_NOTIFY(18),
    /**
     * <pre>
     * 群聊相关
     * </pre>
     *
     * <code>CMD_C2G_REQ = 32;</code>
     */
    CMD_C2G_REQ(32),
    /**
     * <pre>
     * S→C 群聊发送响应
     * </pre>
     *
     * <code>CMD_C2G_RESP = 33;</code>
     */
    CMD_C2G_RESP(33),
    /**
     * <pre>
     * S→C 群聊消息推送
     * </pre>
     *
     * <code>CMD_C2G_NOTIFY = 34;</code>
     */
    CMD_C2G_NOTIFY(34),
    /**
     * <pre>
     * 消息拉取
     * </pre>
     *
     * <code>CMD_PULL_REQ = 48;</code>
     */
    CMD_PULL_REQ(48),
    /**
     * <pre>
     * S→C 拉取离线消息响应
     * </pre>
     *
     * <code>CMD_PULL_RESP = 49;</code>
     */
    CMD_PULL_RESP(49),
    /**
     * <pre>
     * 控制命令
     * </pre>
     *
     * <code>CMD_CTRL_REQ = 64;</code>
     */
    CMD_CTRL_REQ(64),
    /**
     * <pre>
     * S→C 控制命令响应
     * </pre>
     *
     * <code>CMD_CTRL_RESP = 65;</code>
     */
    CMD_CTRL_RESP(65),
    /**
     * <pre>
     * S→C 控制命令推送
     * </pre>
     *
     * <code>CMD_CTRL_NOTIFY = 66;</code>
     */
    CMD_CTRL_NOTIFY(66),
    /**
     * <pre>
     * 心跳与确认
     * </pre>
     *
     * <code>CMD_PING = 80;</code>
     */
    CMD_PING(80),
    /**
     * <pre>
     * S→C 心跳响应
     * </pre>
     *
     * <code>CMD_PONG = 81;</code>
     */
    CMD_PONG(81),
    /**
     * <pre>
     * ACK消息确认请求
     * </pre>
     *
     * <code>CMD_ACK_REQ = 82;</code>
     */
    CMD_ACK_REQ(82),
    /**
     * <pre>
     * ACK消息确认响应
     * </pre>
     *
     * <code>CMD_ACK_RESP = 83;</code>
     */
    CMD_ACK_RESP(83),
    /**
     * <pre>
     * ACK消息确认推送
     * </pre>
     *
     * <code>CMD_ACK_NOTIFY = 84;</code>
     */
    CMD_ACK_NOTIFY(84),
    /**
     * <pre>
     * 好友关系
     * </pre>
     *
     * <code>CMD_FRIEND_SEARCH_REQ = 96;</code>
     */
    CMD_FRIEND_SEARCH_REQ(96),
    /**
     * <pre>
     * S→C 搜索用户响应
     * </pre>
     *
     * <code>CMD_FRIEND_SEARCH_RESP = 97;</code>
     */
    CMD_FRIEND_SEARCH_RESP(97),
    /**
     * <pre>
     * C→S 添加好友请求
     * </pre>
     *
     * <code>CMD_FRIEND_ADD_REQ = 98;</code>
     */
    CMD_FRIEND_ADD_REQ(98),
    /**
     * <pre>
     * S→C 添加好友响应
     * </pre>
     *
     * <code>CMD_FRIEND_ADD_RESP = 99;</code>
     */
    CMD_FRIEND_ADD_RESP(99),
    /**
     * <pre>
     * S→C 好友申请推送
     * </pre>
     *
     * <code>CMD_FRIEND_ADD_NOTIFY = 100;</code>
     */
    CMD_FRIEND_ADD_NOTIFY(100),
    /**
     * <pre>
     * C→S 接受好友请求
     * </pre>
     *
     * <code>CMD_FRIEND_ACCEPT_REQ = 101;</code>
     */
    CMD_FRIEND_ACCEPT_REQ(101),
    /**
     * <pre>
     * S→C 接受好友响应
     * </pre>
     *
     * <code>CMD_FRIEND_ACCEPT_RESP = 102;</code>
     */
    CMD_FRIEND_ACCEPT_RESP(102),
    /**
     * <pre>
     * S→C 接受好友推送
     * </pre>
     *
     * <code>CMD_FRIEND_ACCEPT_NOTIFY = 103;</code>
     */
    CMD_FRIEND_ACCEPT_NOTIFY(103),
    /**
     * <pre>
     * C→S 删除好友请求
     * </pre>
     *
     * <code>CMD_FRIEND_DELETE_REQ = 104;</code>
     */
    CMD_FRIEND_DELETE_REQ(104),
    /**
     * <pre>
     * S→C 删除好友响应
     * </pre>
     *
     * <code>CMD_FRIEND_DELETE_RESP = 105;</code>
     */
    CMD_FRIEND_DELETE_RESP(105),
    /**
     * <pre>
     * S→C 删除好友推送
     * </pre>
     *
     * <code>CMD_FRIEND_DELETE_NOTIFY = 106;</code>
     */
    CMD_FRIEND_DELETE_NOTIFY(106),
    /**
     * <pre>
     * S→C 通用错误响应
     * </pre>
     *
     * <code>CMD_ERROR = 65535;</code>
     */
    CMD_ERROR(65535),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CMD_UNKNOWN = 0;</code>
     */
    public static final int CMD_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 认证相关
     * </pre>
     *
     * <code>CMD_AUTH_REQ = 1;</code>
     */
    public static final int CMD_AUTH_REQ_VALUE = 1;
    /**
     * <pre>
     * S→C 认证响应
     * </pre>
     *
     * <code>CMD_AUTH_RESP = 2;</code>
     */
    public static final int CMD_AUTH_RESP_VALUE = 2;
    /**
     * <pre>
     * C→S 登出请求
     * </pre>
     *
     * <code>CMD_LOGOUT_REQ = 3;</code>
     */
    public static final int CMD_LOGOUT_REQ_VALUE = 3;
    /**
     * <pre>
     * S→C 登出响应
     * </pre>
     *
     * <code>CMD_LOGOUT_RESP = 4;</code>
     */
    public static final int CMD_LOGOUT_RESP_VALUE = 4;
    /**
     * <pre>
     * 单聊相关
     * </pre>
     *
     * <code>CMD_C2C_REQ = 16;</code>
     */
    public static final int CMD_C2C_REQ_VALUE = 16;
    /**
     * <pre>
     * S→C 单聊发送响应
     * </pre>
     *
     * <code>CMD_C2C_RESP = 17;</code>
     */
    public static final int CMD_C2C_RESP_VALUE = 17;
    /**
     * <pre>
     * S→C 单聊消息推送
     * </pre>
     *
     * <code>CMD_C2C_NOTIFY = 18;</code>
     */
    public static final int CMD_C2C_NOTIFY_VALUE = 18;
    /**
     * <pre>
     * 群聊相关
     * </pre>
     *
     * <code>CMD_C2G_REQ = 32;</code>
     */
    public static final int CMD_C2G_REQ_VALUE = 32;
    /**
     * <pre>
     * S→C 群聊发送响应
     * </pre>
     *
     * <code>CMD_C2G_RESP = 33;</code>
     */
    public static final int CMD_C2G_RESP_VALUE = 33;
    /**
     * <pre>
     * S→C 群聊消息推送
     * </pre>
     *
     * <code>CMD_C2G_NOTIFY = 34;</code>
     */
    public static final int CMD_C2G_NOTIFY_VALUE = 34;
    /**
     * <pre>
     * 消息拉取
     * </pre>
     *
     * <code>CMD_PULL_REQ = 48;</code>
     */
    public static final int CMD_PULL_REQ_VALUE = 48;
    /**
     * <pre>
     * S→C 拉取离线消息响应
     * </pre>
     *
     * <code>CMD_PULL_RESP = 49;</code>
     */
    public static final int CMD_PULL_RESP_VALUE = 49;
    /**
     * <pre>
     * 控制命令
     * </pre>
     *
     * <code>CMD_CTRL_REQ = 64;</code>
     */
    public static final int CMD_CTRL_REQ_VALUE = 64;
    /**
     * <pre>
     * S→C 控制命令响应
     * </pre>
     *
     * <code>CMD_CTRL_RESP = 65;</code>
     */
    public static final int CMD_CTRL_RESP_VALUE = 65;
    /**
     * <pre>
     * S→C 控制命令推送
     * </pre>
     *
     * <code>CMD_CTRL_NOTIFY = 66;</code>
     */
    public static final int CMD_CTRL_NOTIFY_VALUE = 66;
    /**
     * <pre>
     * 心跳与确认
     * </pre>
     *
     * <code>CMD_PING = 80;</code>
     */
    public static final int CMD_PING_VALUE = 80;
    /**
     * <pre>
     * S→C 心跳响应
     * </pre>
     *
     * <code>CMD_PONG = 81;</code>
     */
    public static final int CMD_PONG_VALUE = 81;
    /**
     * <pre>
     * ACK消息确认请求
     * </pre>
     *
     * <code>CMD_ACK_REQ = 82;</code>
     */
    public static final int CMD_ACK_REQ_VALUE = 82;
    /**
     * <pre>
     * ACK消息确认响应
     * </pre>
     *
     * <code>CMD_ACK_RESP = 83;</code>
     */
    public static final int CMD_ACK_RESP_VALUE = 83;
    /**
     * <pre>
     * ACK消息确认推送
     * </pre>
     *
     * <code>CMD_ACK_NOTIFY = 84;</code>
     */
    public static final int CMD_ACK_NOTIFY_VALUE = 84;
    /**
     * <pre>
     * 好友关系
     * </pre>
     *
     * <code>CMD_FRIEND_SEARCH_REQ = 96;</code>
     */
    public static final int CMD_FRIEND_SEARCH_REQ_VALUE = 96;
    /**
     * <pre>
     * S→C 搜索用户响应
     * </pre>
     *
     * <code>CMD_FRIEND_SEARCH_RESP = 97;</code>
     */
    public static final int CMD_FRIEND_SEARCH_RESP_VALUE = 97;
    /**
     * <pre>
     * C→S 添加好友请求
     * </pre>
     *
     * <code>CMD_FRIEND_ADD_REQ = 98;</code>
     */
    public static final int CMD_FRIEND_ADD_REQ_VALUE = 98;
    /**
     * <pre>
     * S→C 添加好友响应
     * </pre>
     *
     * <code>CMD_FRIEND_ADD_RESP = 99;</code>
     */
    public static final int CMD_FRIEND_ADD_RESP_VALUE = 99;
    /**
     * <pre>
     * S→C 好友申请推送
     * </pre>
     *
     * <code>CMD_FRIEND_ADD_NOTIFY = 100;</code>
     */
    public static final int CMD_FRIEND_ADD_NOTIFY_VALUE = 100;
    /**
     * <pre>
     * C→S 接受好友请求
     * </pre>
     *
     * <code>CMD_FRIEND_ACCEPT_REQ = 101;</code>
     */
    public static final int CMD_FRIEND_ACCEPT_REQ_VALUE = 101;
    /**
     * <pre>
     * S→C 接受好友响应
     * </pre>
     *
     * <code>CMD_FRIEND_ACCEPT_RESP = 102;</code>
     */
    public static final int CMD_FRIEND_ACCEPT_RESP_VALUE = 102;
    /**
     * <pre>
     * S→C 接受好友推送
     * </pre>
     *
     * <code>CMD_FRIEND_ACCEPT_NOTIFY = 103;</code>
     */
    public static final int CMD_FRIEND_ACCEPT_NOTIFY_VALUE = 103;
    /**
     * <pre>
     * C→S 删除好友请求
     * </pre>
     *
     * <code>CMD_FRIEND_DELETE_REQ = 104;</code>
     */
    public static final int CMD_FRIEND_DELETE_REQ_VALUE = 104;
    /**
     * <pre>
     * S→C 删除好友响应
     * </pre>
     *
     * <code>CMD_FRIEND_DELETE_RESP = 105;</code>
     */
    public static final int CMD_FRIEND_DELETE_RESP_VALUE = 105;
    /**
     * <pre>
     * S→C 删除好友推送
     * </pre>
     *
     * <code>CMD_FRIEND_DELETE_NOTIFY = 106;</code>
     */
    public static final int CMD_FRIEND_DELETE_NOTIFY_VALUE = 106;
    /**
     * <pre>
     * S→C 通用错误响应
     * </pre>
     *
     * <code>CMD_ERROR = 65535;</code>
     */
    public static final int CMD_ERROR_VALUE = 65535;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cmd valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Cmd forNumber(int value) {
      switch (value) {
        case 0: return CMD_UNKNOWN;
        case 1: return CMD_AUTH_REQ;
        case 2: return CMD_AUTH_RESP;
        case 3: return CMD_LOGOUT_REQ;
        case 4: return CMD_LOGOUT_RESP;
        case 16: return CMD_C2C_REQ;
        case 17: return CMD_C2C_RESP;
        case 18: return CMD_C2C_NOTIFY;
        case 32: return CMD_C2G_REQ;
        case 33: return CMD_C2G_RESP;
        case 34: return CMD_C2G_NOTIFY;
        case 48: return CMD_PULL_REQ;
        case 49: return CMD_PULL_RESP;
        case 64: return CMD_CTRL_REQ;
        case 65: return CMD_CTRL_RESP;
        case 66: return CMD_CTRL_NOTIFY;
        case 80: return CMD_PING;
        case 81: return CMD_PONG;
        case 82: return CMD_ACK_REQ;
        case 83: return CMD_ACK_RESP;
        case 84: return CMD_ACK_NOTIFY;
        case 96: return CMD_FRIEND_SEARCH_REQ;
        case 97: return CMD_FRIEND_SEARCH_RESP;
        case 98: return CMD_FRIEND_ADD_REQ;
        case 99: return CMD_FRIEND_ADD_RESP;
        case 100: return CMD_FRIEND_ADD_NOTIFY;
        case 101: return CMD_FRIEND_ACCEPT_REQ;
        case 102: return CMD_FRIEND_ACCEPT_RESP;
        case 103: return CMD_FRIEND_ACCEPT_NOTIFY;
        case 104: return CMD_FRIEND_DELETE_REQ;
        case 105: return CMD_FRIEND_DELETE_RESP;
        case 106: return CMD_FRIEND_DELETE_NOTIFY;
        case 65535: return CMD_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
            public Cmd findValueByNumber(int number) {
              return Cmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.common.CommonProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Cmd[] VALUES = values();

    public static Cmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.common.Cmd)
  }

  /**
   * <pre>
   * ============================================================================
   * 消息类型（MsgType）枚举定义
   * ============================================================================
   * </pre>
   *
   * Protobuf enum {@code im.common.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_TYPE_UNKNOWN = 0;</code>
     */
    MSG_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 纯文本
     * </pre>
     *
     * <code>MSG_TYPE_TEXT = 1;</code>
     */
    MSG_TYPE_TEXT(1),
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>MSG_TYPE_IMAGE = 2;</code>
     */
    MSG_TYPE_IMAGE(2),
    /**
     * <pre>
     * 语音
     * </pre>
     *
     * <code>MSG_TYPE_VOICE = 3;</code>
     */
    MSG_TYPE_VOICE(3),
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>MSG_TYPE_VIDEO = 4;</code>
     */
    MSG_TYPE_VIDEO(4),
    /**
     * <pre>
     * 文件
     * </pre>
     *
     * <code>MSG_TYPE_FILE = 5;</code>
     */
    MSG_TYPE_FILE(5),
    /**
     * <pre>
     * 表情
     * </pre>
     *
     * <code>MSG_TYPE_EMOJI = 6;</code>
     */
    MSG_TYPE_EMOJI(6),
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>MSG_TYPE_SYSTEM = 7;</code>
     */
    MSG_TYPE_SYSTEM(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MSG_TYPE_UNKNOWN = 0;</code>
     */
    public static final int MSG_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 纯文本
     * </pre>
     *
     * <code>MSG_TYPE_TEXT = 1;</code>
     */
    public static final int MSG_TYPE_TEXT_VALUE = 1;
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>MSG_TYPE_IMAGE = 2;</code>
     */
    public static final int MSG_TYPE_IMAGE_VALUE = 2;
    /**
     * <pre>
     * 语音
     * </pre>
     *
     * <code>MSG_TYPE_VOICE = 3;</code>
     */
    public static final int MSG_TYPE_VOICE_VALUE = 3;
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>MSG_TYPE_VIDEO = 4;</code>
     */
    public static final int MSG_TYPE_VIDEO_VALUE = 4;
    /**
     * <pre>
     * 文件
     * </pre>
     *
     * <code>MSG_TYPE_FILE = 5;</code>
     */
    public static final int MSG_TYPE_FILE_VALUE = 5;
    /**
     * <pre>
     * 表情
     * </pre>
     *
     * <code>MSG_TYPE_EMOJI = 6;</code>
     */
    public static final int MSG_TYPE_EMOJI_VALUE = 6;
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>MSG_TYPE_SYSTEM = 7;</code>
     */
    public static final int MSG_TYPE_SYSTEM_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return MSG_TYPE_UNKNOWN;
        case 1: return MSG_TYPE_TEXT;
        case 2: return MSG_TYPE_IMAGE;
        case 3: return MSG_TYPE_VOICE;
        case 4: return MSG_TYPE_VIDEO;
        case 5: return MSG_TYPE_FILE;
        case 6: return MSG_TYPE_EMOJI;
        case 7: return MSG_TYPE_SYSTEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.common.CommonProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.common.MsgType)
  }

  /**
   * Protobuf enum {@code im.common.AckType}
   */
  public enum AckType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 已收到
     * </pre>
     *
     * <code>RECEIVED = 0;</code>
     */
    RECEIVED(0),
    /**
     * <pre>
     * 已读
     * </pre>
     *
     * <code>SEEN = 1;</code>
     */
    SEEN(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 已收到
     * </pre>
     *
     * <code>RECEIVED = 0;</code>
     */
    public static final int RECEIVED_VALUE = 0;
    /**
     * <pre>
     * 已读
     * </pre>
     *
     * <code>SEEN = 1;</code>
     */
    public static final int SEEN_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AckType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AckType forNumber(int value) {
      switch (value) {
        case 0: return RECEIVED;
        case 1: return SEEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AckType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AckType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AckType>() {
            public AckType findValueByNumber(int number) {
              return AckType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.common.CommonProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final AckType[] VALUES = values();

    public static AckType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AckType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.common.AckType)
  }

  public interface MessageContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.common.MessageContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.im.common.MsgType msg_type = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.im.common.MsgType msg_type = 1;</code>
     * @return The msgType.
     */
    com.github.moxib.pomelo.proto.common.CommonProto.MsgType getMsgType();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <pre>
     * 消息时间戳（Unix 毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    int getExtCount();
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    boolean containsExt(
        java.lang.String key);
    /**
     * Use {@link #getExtMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getExt();
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getExtMap();
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    /* nullable */
java.lang.String getExtOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    java.lang.String getExtOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * ============================================================================
   * 通用消息内容结构
   * ============================================================================
   * </pre>
   *
   * Protobuf type {@code im.common.MessageContent}
   */
  public static final class MessageContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.common.MessageContent)
      MessageContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageContent.newBuilder() to construct.
    private MessageContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageContent() {
      msgType_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageContent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_MessageContent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetExt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_MessageContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.class, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder.class);
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.im.common.MsgType msg_type = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.im.common.MsgType msg_type = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override public com.github.moxib.pomelo.proto.common.CommonProto.MsgType getMsgType() {
      com.github.moxib.pomelo.proto.common.CommonProto.MsgType result = com.github.moxib.pomelo.proto.common.CommonProto.MsgType.forNumber(msgType_);
      return result == null ? com.github.moxib.pomelo.proto.common.CommonProto.MsgType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_ = 0L;
    /**
     * <pre>
     * 消息时间戳（Unix 毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int EXT_FIELD_NUMBER = 4;
    private static final class ExtDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_MessageContent_ExtEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> ext_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExt() {
      if (ext_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtDefaultEntryHolder.defaultEntry);
      }
      return ext_;
    }
    public int getExtCount() {
      return internalGetExt().getMap().size();
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    @java.lang.Override
    public boolean containsExt(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExt() {
      return getExtMap();
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
      return internalGetExt().getMap();
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getExtOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getExtOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != com.github.moxib.pomelo.proto.common.CommonProto.MsgType.MSG_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExt(),
          ExtDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != com.github.moxib.pomelo.proto.common.CommonProto.MsgType.MSG_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetExt().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        ext__ = ExtDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, ext__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.common.CommonProto.MessageContent)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.common.CommonProto.MessageContent other = (com.github.moxib.pomelo.proto.common.CommonProto.MessageContent) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!internalGetExt().equals(
          other.internalGetExt())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (!internalGetExt().getMap().isEmpty()) {
        hash = (37 * hash) + EXT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.common.CommonProto.MessageContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ============================================================================
     * 通用消息内容结构
     * ============================================================================
     * </pre>
     *
     * Protobuf type {@code im.common.MessageContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.common.MessageContent)
        com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_MessageContent_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetExt();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableExt();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_MessageContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.class, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgType_ = 0;
        content_ = com.google.protobuf.ByteString.EMPTY;
        timestamp_ = 0L;
        internalGetMutableExt().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_MessageContent_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent build() {
        com.github.moxib.pomelo.proto.common.CommonProto.MessageContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent buildPartial() {
        com.github.moxib.pomelo.proto.common.CommonProto.MessageContent result = new com.github.moxib.pomelo.proto.common.CommonProto.MessageContent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.common.CommonProto.MessageContent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgType_ = msgType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ext_ = internalGetExt();
          result.ext_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.common.CommonProto.MessageContent) {
          return mergeFrom((com.github.moxib.pomelo.proto.common.CommonProto.MessageContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.common.CommonProto.MessageContent other) {
        if (other == com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        internalGetMutableExt().mergeFrom(
            other.internalGetExt());
        bitField0_ |= 0x00000008;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                content_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                ext__ = input.readMessage(
                    ExtDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableExt().getMutableMap().put(
                    ext__.getKey(), ext__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int msgType_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.im.common.MsgType msg_type = 1;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.im.common.MsgType msg_type = 1;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.im.common.MsgType msg_type = 1;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.MsgType getMsgType() {
        com.github.moxib.pomelo.proto.common.CommonProto.MsgType result = com.github.moxib.pomelo.proto.common.CommonProto.MsgType.forNumber(msgType_);
        return result == null ? com.github.moxib.pomelo.proto.common.CommonProto.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.im.common.MsgType msg_type = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(com.github.moxib.pomelo.proto.common.CommonProto.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.im.common.MsgType msg_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>bytes content = 2;</code>
       * @return The content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>bytes content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>bytes content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 消息时间戳（Unix 毫秒）
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 消息时间戳（Unix 毫秒）
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息时间戳（Unix 毫秒）
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> ext_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetExt() {
        if (ext_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtDefaultEntryHolder.defaultEntry);
        }
        return ext_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableExt() {
        if (ext_ == null) {
          ext_ = com.google.protobuf.MapField.newMapField(
              ExtDefaultEntryHolder.defaultEntry);
        }
        if (!ext_.isMutable()) {
          ext_ = ext_.copy();
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return ext_;
      }
      public int getExtCount() {
        return internalGetExt().getMap().size();
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      @java.lang.Override
      public boolean containsExt(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetExt().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getExt() {
        return getExtMap();
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
        return internalGetExt().getMap();
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getExtOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExt().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      @java.lang.Override
      public java.lang.String getExtOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExt().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearExt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableExt().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      public Builder removeExt(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableExt().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableExt() {
        bitField0_ |= 0x00000008;
        return internalGetMutableExt().getMutableMap();
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      public Builder putExt(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableExt().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 4;</code>
       */
      public Builder putAllExt(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableExt().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.common.MessageContent)
    }

    // @@protoc_insertion_point(class_scope:im.common.MessageContent)
    private static final com.github.moxib.pomelo.proto.common.CommonProto.MessageContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.common.CommonProto.MessageContent();
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.MessageContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageContent>
        PARSER = new com.google.protobuf.AbstractParser<MessageContent>() {
      @java.lang.Override
      public MessageContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageContent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.common.ErrorBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * ============================================================================
   * 通用错误响应体
   * ============================================================================
   * </pre>
   *
   * Protobuf type {@code im.common.ErrorBody}
   */
  public static final class ErrorBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.common.ErrorBody)
      ErrorBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorBody.newBuilder() to construct.
    private ErrorBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorBody() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ErrorBody();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_ErrorBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_ErrorBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.class, com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody other = (com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ============================================================================
     * 通用错误响应体
     * ============================================================================
     * </pre>
     *
     * Protobuf type {@code im.common.ErrorBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.common.ErrorBody)
        com.github.moxib.pomelo.proto.common.CommonProto.ErrorBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_ErrorBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_ErrorBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.class, com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.common.CommonProto.internal_static_im_common_ErrorBody_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody build() {
        com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody buildPartial() {
        com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody result = new com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody) {
          return mergeFrom((com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody other) {
        if (other == com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.common.ErrorBody)
    }

    // @@protoc_insertion_point(class_scope:im.common.ErrorBody)
    private static final com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody();
    }

    public static com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorBody>
        PARSER = new com.google.protobuf.AbstractParser<ErrorBody>() {
      @java.lang.Override
      public ErrorBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ErrorBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.common.CommonProto.ErrorBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_common_MessageContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_common_MessageContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_common_MessageContent_ExtEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_common_MessageContent_ExtEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_common_ErrorBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_common_ErrorBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common/common.proto\022\tim.common\"\267\001\n\016Mes" +
      "sageContent\022$\n\010msg_type\030\001 \001(\0162\022.im.commo" +
      "n.MsgType\022\017\n\007content\030\002 \001(\014\022\021\n\ttimestamp\030" +
      "\003 \001(\003\022/\n\003ext\030\004 \003(\0132\".im.common.MessageCo" +
      "ntent.ExtEntry\032*\n\010ExtEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"*\n\tErrorBody\022\014\n\004code\030" +
      "\001 \001(\005\022\017\n\007message\030\002 \001(\t*\302\005\n\003Cmd\022\017\n\013CMD_UN" +
      "KNOWN\020\000\022\020\n\014CMD_AUTH_REQ\020\001\022\021\n\rCMD_AUTH_RE" +
      "SP\020\002\022\022\n\016CMD_LOGOUT_REQ\020\003\022\023\n\017CMD_LOGOUT_R" +
      "ESP\020\004\022\017\n\013CMD_C2C_REQ\020\020\022\020\n\014CMD_C2C_RESP\020\021" +
      "\022\022\n\016CMD_C2C_NOTIFY\020\022\022\017\n\013CMD_C2G_REQ\020 \022\020\n" +
      "\014CMD_C2G_RESP\020!\022\022\n\016CMD_C2G_NOTIFY\020\"\022\020\n\014C" +
      "MD_PULL_REQ\0200\022\021\n\rCMD_PULL_RESP\0201\022\020\n\014CMD_" +
      "CTRL_REQ\020@\022\021\n\rCMD_CTRL_RESP\020A\022\023\n\017CMD_CTR" +
      "L_NOTIFY\020B\022\014\n\010CMD_PING\020P\022\014\n\010CMD_PONG\020Q\022\017" +
      "\n\013CMD_ACK_REQ\020R\022\020\n\014CMD_ACK_RESP\020S\022\022\n\016CMD" +
      "_ACK_NOTIFY\020T\022\031\n\025CMD_FRIEND_SEARCH_REQ\020`" +
      "\022\032\n\026CMD_FRIEND_SEARCH_RESP\020a\022\026\n\022CMD_FRIE" +
      "ND_ADD_REQ\020b\022\027\n\023CMD_FRIEND_ADD_RESP\020c\022\031\n" +
      "\025CMD_FRIEND_ADD_NOTIFY\020d\022\031\n\025CMD_FRIEND_A" +
      "CCEPT_REQ\020e\022\032\n\026CMD_FRIEND_ACCEPT_RESP\020f\022" +
      "\034\n\030CMD_FRIEND_ACCEPT_NOTIFY\020g\022\031\n\025CMD_FRI" +
      "END_DELETE_REQ\020h\022\032\n\026CMD_FRIEND_DELETE_RE" +
      "SP\020i\022\034\n\030CMD_FRIEND_DELETE_NOTIFY\020j\022\017\n\tCM" +
      "D_ERROR\020\377\377\003*\252\001\n\007MsgType\022\024\n\020MSG_TYPE_UNKN" +
      "OWN\020\000\022\021\n\rMSG_TYPE_TEXT\020\001\022\022\n\016MSG_TYPE_IMA" +
      "GE\020\002\022\022\n\016MSG_TYPE_VOICE\020\003\022\022\n\016MSG_TYPE_VID" +
      "EO\020\004\022\021\n\rMSG_TYPE_FILE\020\005\022\022\n\016MSG_TYPE_EMOJ" +
      "I\020\006\022\023\n\017MSG_TYPE_SYSTEM\020\007*!\n\007AckType\022\014\n\010R" +
      "ECEIVED\020\000\022\010\n\004SEEN\020\001B3\n$com.github.moxib." +
      "pomelo.proto.commonB\013CommonProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_common_MessageContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_common_MessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_common_MessageContent_descriptor,
        new java.lang.String[] { "MsgType", "Content", "Timestamp", "Ext", });
    internal_static_im_common_MessageContent_ExtEntry_descriptor =
      internal_static_im_common_MessageContent_descriptor.getNestedTypes().get(0);
    internal_static_im_common_MessageContent_ExtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_common_MessageContent_ExtEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_im_common_ErrorBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_im_common_ErrorBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_common_ErrorBody_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
