// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pull/pull.proto

// Protobuf Java Version: 3.25.5
package com.github.moxib.pomelo.proto.pull;

public final class PullProto {
  private PullProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PullReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.pull.PullReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 拉取数量限制
     * </pre>
     *
     * <code>int32 limit = 1;</code>
     * @return The limit.
     */
    int getLimit();

    /**
     * <pre>
     * 最后一条消息 ID
     * </pre>
     *
     * <code>int64 last_msg_id = 2;</code>
     * @return The lastMsgId.
     */
    long getLastMsgId();
  }
  /**
   * <pre>
   * ============================================================================
   * 消息拉取相关消息体
   * ============================================================================
   * </pre>
   *
   * Protobuf type {@code im.pull.PullReq}
   */
  public static final class PullReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.pull.PullReq)
      PullReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PullReq.newBuilder() to construct.
    private PullReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PullReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.pull.PullProto.PullReq.class, com.github.moxib.pomelo.proto.pull.PullProto.PullReq.Builder.class);
    }

    public static final int LIMIT_FIELD_NUMBER = 1;
    private int limit_ = 0;
    /**
     * <pre>
     * 拉取数量限制
     * </pre>
     *
     * <code>int32 limit = 1;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }

    public static final int LAST_MSG_ID_FIELD_NUMBER = 2;
    private long lastMsgId_ = 0L;
    /**
     * <pre>
     * 最后一条消息 ID
     * </pre>
     *
     * <code>int64 last_msg_id = 2;</code>
     * @return The lastMsgId.
     */
    @java.lang.Override
    public long getLastMsgId() {
      return lastMsgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (limit_ != 0) {
        output.writeInt32(1, limit_);
      }
      if (lastMsgId_ != 0L) {
        output.writeInt64(2, lastMsgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, limit_);
      }
      if (lastMsgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastMsgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.pull.PullProto.PullReq)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.pull.PullProto.PullReq other = (com.github.moxib.pomelo.proto.pull.PullProto.PullReq) obj;

      if (getLimit()
          != other.getLimit()) return false;
      if (getLastMsgId()
          != other.getLastMsgId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + LAST_MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastMsgId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.pull.PullProto.PullReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ============================================================================
     * 消息拉取相关消息体
     * ============================================================================
     * </pre>
     *
     * Protobuf type {@code im.pull.PullReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.pull.PullReq)
        com.github.moxib.pomelo.proto.pull.PullProto.PullReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.pull.PullProto.PullReq.class, com.github.moxib.pomelo.proto.pull.PullProto.PullReq.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.pull.PullProto.PullReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        limit_ = 0;
        lastMsgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullReq_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.pull.PullProto.PullReq getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.pull.PullProto.PullReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.pull.PullProto.PullReq build() {
        com.github.moxib.pomelo.proto.pull.PullProto.PullReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.pull.PullProto.PullReq buildPartial() {
        com.github.moxib.pomelo.proto.pull.PullProto.PullReq result = new com.github.moxib.pomelo.proto.pull.PullProto.PullReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.pull.PullProto.PullReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.limit_ = limit_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lastMsgId_ = lastMsgId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.pull.PullProto.PullReq) {
          return mergeFrom((com.github.moxib.pomelo.proto.pull.PullProto.PullReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.pull.PullProto.PullReq other) {
        if (other == com.github.moxib.pomelo.proto.pull.PullProto.PullReq.getDefaultInstance()) return this;
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (other.getLastMsgId() != 0L) {
          setLastMsgId(other.getLastMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                limit_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                lastMsgId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int limit_ ;
      /**
       * <pre>
       * 拉取数量限制
       * </pre>
       *
       * <code>int32 limit = 1;</code>
       * @return The limit.
       */
      @java.lang.Override
      public int getLimit() {
        return limit_;
      }
      /**
       * <pre>
       * 拉取数量限制
       * </pre>
       *
       * <code>int32 limit = 1;</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(int value) {

        limit_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 拉取数量限制
       * </pre>
       *
       * <code>int32 limit = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        limit_ = 0;
        onChanged();
        return this;
      }

      private long lastMsgId_ ;
      /**
       * <pre>
       * 最后一条消息 ID
       * </pre>
       *
       * <code>int64 last_msg_id = 2;</code>
       * @return The lastMsgId.
       */
      @java.lang.Override
      public long getLastMsgId() {
        return lastMsgId_;
      }
      /**
       * <pre>
       * 最后一条消息 ID
       * </pre>
       *
       * <code>int64 last_msg_id = 2;</code>
       * @param value The lastMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setLastMsgId(long value) {

        lastMsgId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最后一条消息 ID
       * </pre>
       *
       * <code>int64 last_msg_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastMsgId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastMsgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.pull.PullReq)
    }

    // @@protoc_insertion_point(class_scope:im.pull.PullReq)
    private static final com.github.moxib.pomelo.proto.pull.PullProto.PullReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.pull.PullProto.PullReq();
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullReq>
        PARSER = new com.google.protobuf.AbstractParser<PullReq>() {
      @java.lang.Override
      public PullReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PullReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.pull.PullProto.PullReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PullRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.pull.PullResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 响应码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    java.util.List<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent> 
        getMessagesList();
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    com.github.moxib.pomelo.proto.common.CommonProto.MessageContent getMessages(int index);
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    int getMessagesCount();
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    java.util.List<? extends com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder getMessagesOrBuilder(
        int index);

    /**
     * <pre>
     * 是否还有更多
     * </pre>
     *
     * <code>bool has_more = 4;</code>
     * @return The hasMore.
     */
    boolean getHasMore();
  }
  /**
   * Protobuf type {@code im.pull.PullResp}
   */
  public static final class PullResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.pull.PullResp)
      PullRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PullResp.newBuilder() to construct.
    private PullResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullResp() {
      message_ = "";
      messages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PullResp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.moxib.pomelo.proto.pull.PullProto.PullResp.class, com.github.moxib.pomelo.proto.pull.PullProto.PullResp.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <pre>
     * 响应码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent> messages_;
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent> getMessagesList() {
      return messages_;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    @java.lang.Override
    public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .im.common.MessageContent messages = 3;</code>
     */
    @java.lang.Override
    public com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    public static final int HAS_MORE_FIELD_NUMBER = 4;
    private boolean hasMore_ = false;
    /**
     * <pre>
     * 是否还有更多
     * </pre>
     *
     * <code>bool has_more = 4;</code>
     * @return The hasMore.
     */
    @java.lang.Override
    public boolean getHasMore() {
      return hasMore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(3, messages_.get(i));
      }
      if (hasMore_ != false) {
        output.writeBool(4, hasMore_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, messages_.get(i));
      }
      if (hasMore_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasMore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.moxib.pomelo.proto.pull.PullProto.PullResp)) {
        return super.equals(obj);
      }
      com.github.moxib.pomelo.proto.pull.PullProto.PullResp other = (com.github.moxib.pomelo.proto.pull.PullProto.PullResp) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (getHasMore()
          != other.getHasMore()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (37 * hash) + HAS_MORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasMore());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.moxib.pomelo.proto.pull.PullProto.PullResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.pull.PullResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.pull.PullResp)
        com.github.moxib.pomelo.proto.pull.PullProto.PullRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.moxib.pomelo.proto.pull.PullProto.PullResp.class, com.github.moxib.pomelo.proto.pull.PullProto.PullResp.Builder.class);
      }

      // Construct using com.github.moxib.pomelo.proto.pull.PullProto.PullResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
        } else {
          messages_ = null;
          messagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        hasMore_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.moxib.pomelo.proto.pull.PullProto.internal_static_im_pull_PullResp_descriptor;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.pull.PullProto.PullResp getDefaultInstanceForType() {
        return com.github.moxib.pomelo.proto.pull.PullProto.PullResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.pull.PullProto.PullResp build() {
        com.github.moxib.pomelo.proto.pull.PullProto.PullResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.moxib.pomelo.proto.pull.PullProto.PullResp buildPartial() {
        com.github.moxib.pomelo.proto.pull.PullProto.PullResp result = new com.github.moxib.pomelo.proto.pull.PullProto.PullResp(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.github.moxib.pomelo.proto.pull.PullProto.PullResp result) {
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
      }

      private void buildPartial0(com.github.moxib.pomelo.proto.pull.PullProto.PullResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hasMore_ = hasMore_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.moxib.pomelo.proto.pull.PullProto.PullResp) {
          return mergeFrom((com.github.moxib.pomelo.proto.pull.PullProto.PullResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.moxib.pomelo.proto.pull.PullProto.PullResp other) {
        if (other == com.github.moxib.pomelo.proto.pull.PullProto.PullResp.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000004);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        if (other.getHasMore() != false) {
          setHasMore(other.getHasMore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.github.moxib.pomelo.proto.common.CommonProto.MessageContent m =
                    input.readMessage(
                        com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.parser(),
                        extensionRegistry);
                if (messagesBuilder_ == null) {
                  ensureMessagesIsMutable();
                  messages_.add(m);
                } else {
                  messagesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              case 32: {
                hasMore_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          messages_ = new java.util.ArrayList<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent>(messages_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.moxib.pomelo.proto.common.CommonProto.MessageContent, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder, com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder> messagesBuilder_;

      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public java.util.List<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder setMessages(
          int index, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder setMessages(
          int index, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder addMessages(com.github.moxib.pomelo.proto.common.CommonProto.MessageContent value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder addMessages(
          int index, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder addMessages(
          com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder addMessages(
          int index, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.github.moxib.pomelo.proto.common.CommonProto.MessageContent> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public java.util.List<? extends com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.getDefaultInstance());
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.getDefaultInstance());
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .im.common.MessageContent messages = 3;</code>
       */
      public java.util.List<com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.moxib.pomelo.proto.common.CommonProto.MessageContent, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder, com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.moxib.pomelo.proto.common.CommonProto.MessageContent, com.github.moxib.pomelo.proto.common.CommonProto.MessageContent.Builder, com.github.moxib.pomelo.proto.common.CommonProto.MessageContentOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      private boolean hasMore_ ;
      /**
       * <pre>
       * 是否还有更多
       * </pre>
       *
       * <code>bool has_more = 4;</code>
       * @return The hasMore.
       */
      @java.lang.Override
      public boolean getHasMore() {
        return hasMore_;
      }
      /**
       * <pre>
       * 是否还有更多
       * </pre>
       *
       * <code>bool has_more = 4;</code>
       * @param value The hasMore to set.
       * @return This builder for chaining.
       */
      public Builder setHasMore(boolean value) {

        hasMore_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否还有更多
       * </pre>
       *
       * <code>bool has_more = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasMore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasMore_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.pull.PullResp)
    }

    // @@protoc_insertion_point(class_scope:im.pull.PullResp)
    private static final com.github.moxib.pomelo.proto.pull.PullProto.PullResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.moxib.pomelo.proto.pull.PullProto.PullResp();
    }

    public static com.github.moxib.pomelo.proto.pull.PullProto.PullResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullResp>
        PARSER = new com.google.protobuf.AbstractParser<PullResp>() {
      @java.lang.Override
      public PullResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PullResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.moxib.pomelo.proto.pull.PullProto.PullResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_pull_PullReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_pull_PullReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_pull_PullResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_pull_PullResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017pull/pull.proto\022\007im.pull\032\023common/commo" +
      "n.proto\"-\n\007PullReq\022\r\n\005limit\030\001 \001(\005\022\023\n\013las" +
      "t_msg_id\030\002 \001(\003\"h\n\010PullResp\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\t\022+\n\010messages\030\003 \003(\0132\031.im" +
      ".common.MessageContent\022\020\n\010has_more\030\004 \001(\010" +
      "B/\n\"com.github.moxib.pomelo.proto.pullB\t" +
      "PullProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.moxib.pomelo.proto.common.CommonProto.getDescriptor(),
        });
    internal_static_im_pull_PullReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_pull_PullReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_pull_PullReq_descriptor,
        new java.lang.String[] { "Limit", "LastMsgId", });
    internal_static_im_pull_PullResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_im_pull_PullResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_pull_PullResp_descriptor,
        new java.lang.String[] { "Code", "Message", "Messages", "HasMore", });
    com.github.moxib.pomelo.proto.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
